module.exports = {
    TOOLDESIGN: {
        //SOLAR_TAB: "span[class='text-sm px-4 py-1.5 rounded-full flex items-center font-interSemiBold cursor-pointer ng-tns-c211-251 bg-white text-bodyColor ng-star-inserted']",
        AI_DESIGN_BUTTON: "button.mat-tooltip-trigger",
        Popup_Yes_Button: "button[type='submit']",
        UTILITY_DROPDOWN: "mat-select[formcontrolname='utility']",
        UTILITY_FIRSTOPTION: "mat-option.mat-active",
        START_DESIGN_BUTTON: "button.mat-tooltip-trigger.salestool_primary__btn",
        RUN_AI_DESIGN_BUTTON: "div.btn-container",
        RUN_AI_DESIGN_NEXT_BUTTON: "button.sc-jIRcFI.JuZhs.save-btn",
        Toggle_Button: "#mat-slide-toggle-1-input",
        Battery_Storage: "[_ngcontent-ciw-c760] .slick-slide",
        CREATE_ACCOUNT_BUTTON: "salestool-button[label='Create Account']",
        SELECT_ESCALATOR_RATE: ".mat-form-field",
        SELECT_RATE_DROPDOWN: ".mat-option.font-interRegular",
        SELECT_PRICING_DROPDOWN: ".mat-select.mat-tooltip-trigger",
        SELECT_PRICING_VALUE: "span.mat-option-text",
        CREATE_QUOTE_BUTTON: ".mat-tooltip-trigger",
        UTILITY_DROPDOWN1: ".mat-select",
        UTILITY_DROPDOWN1_VALUE: ".mat-option",
        SELECT_RATE_DROPDOWN1: "div.mat-form-field-flex.ng-tns-c75-201",
        CREATE_ACCOUNT_BUTTON1: "button.salestool_primary__btn",
        SELECT_RATE_DROPDOWN2: "mat-select.mat-select",
        SELECT_VALUE_RATE_DROPDOWN: "span.mat-option-text",
        CLICK_CREATE_QUOTE_LIGHTREACH: "button.bg-primary",
        CLICK_FINALIZE_BUTTON: "button.flex-1",
        CLICK_QUALIFY_BUTTON: "button.flex-1",
        TYPE_DOB_TEXTBOX: "input.mat-datepicker-input",
        TYPE_SNN_TEXTBOX: "input.salestool__inputCustom",
        TYPE_JOB_TITLE_TEXTBOX: "input.salestool__inputCustom",
        TYPE_JOB_TENURE_MONTHS_TEXTBOX: "input.salestool__inputCustom",
        TYPE_EMPLOYER_NAME_TEXTBOX: "input.salestool__inputCustom",
        CLICK_EMP_STATUS_DROPDOWN: "span.mat-select-placeholder",
        SELECT_VALUE_DROPDOWN: "span.mat-option-text",
        SELECT_FIRST_RADIO_BUTTON: "span.mat-checkbox-inner-container",
        SELECT_SECOND_RADIO_BUTTON: "span.mat-checkbox-inner-container",
        CLICK_SUBMIT_BUTTON_FOR_QUALIFY: "button.mat-badge",
        CLICK_OK_FOR_POPUP: "button.mat-badge"
    }
}